-- Schema SQL untuk menyimpan backup pesan masuk di Supabase Database

CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Policy untuk izinkan Service Role melakukan insert (Edge Function menggunakan Service Role Key)
CREATE POLICY "Allow Edge Function Service Role Insert"
ON public.contacts
FOR INSERT
TO service_role
WITH CHECK (true);
